### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by prashantgupta24** [prashantgupta24/activity-tracker#4]
## Must-haves
- [x] License
- [x] Tests
- [x] Test code coverage
- [x] Handle signals (like mac being put to sleep, tracked [here](https://github.com/prashantgupta24/activity-tracker/issues/7))
- [x] Individual channel for each service
- [x] Whether we need to pass variables to go func or rely on closure
- [x] Refactoring packages
- [x] Screen change handler
- [x] Make service handler as map, check for duplicate service registry
- [x] Introduce timeout for each handler
- [x] services as interfaces
- [x] overloaded start function that accepts services
- [x] introduce logging

## Enhancements
- [ ] Tests CI (facing [issue](https://github.com/prashantgupta24/activity-tracker/issues/17))
- [ ] Multiple event registration (dependent on `robotgo` next release)
- [ ] Include context
- [x] Switch to `go mod`
- [ ] Enhance click handler
- [ ] Enhance screen change with multiple pixels
- [ ] Add channels' direction sense

## Documentation
- [ ] Go docs
- [x] Improve readme
- [x] Add comments
- [x] Add badges

**Comment by prashantgupta24** [comment]
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4264e7c]

runtime stack:
runtime.throw(0x43376a1, 0x2a)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/signal_unix.go:374 +0x2f2

goroutine 3854 [syscall]:
runtime.cgocall(0x426c0c0, 0xc000315f28, 0x3)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc000315ef0 sp=0xc000315eb8 pc=0x4005cfe
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo._Cfunc_get_pixel_color(0x2d0, 0x1c2, 0x0)
        _cgo_gotypes.go:607 +0x4e fp=0xc000315f28 sp=0xc000315ef0 pc=0x425d77e
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo.GetPixelColor(0x2d0, 0x1c2, 0x426037f, 0xc0001b6001)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo/robotgo.go:192 +0x35 fp=0xc000315f68 sp=0xc000315f28 pc=0x425d985
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.checkScreenChange(0xc0000c0780, 0xc00013a088, 0x6, 0x2d0, 0x1c2)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/screenChangeHandler.go:68 +0x39 fp=0xc000315fb8 sp=0xc000315f68 pc=0x42604f9
runtime.goexit()
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000315fc0 sp=0xc000315fb8 pc=0x4059c11
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*screenChangeHandler).Start.func1
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/screenChangeHandler.go:32 +0x1ce

goroutine 1 [syscall, 44 minutes, locked to thread]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/getlantern/systray._Cfunc_nativeLoop(0xc000000000)
        _cgo_gotypes.go:107 +0x49
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/getlantern/systray.nativeLoop()
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/getlantern/systray/systray_nonwindows.go:19 +0x22
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/getlantern/systray.Run(0x433f930, 0x433f920)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/getlantern/systray/systray.go:81 +0x7e
main.main()
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/cmd/main.go:12 +0x39

goroutine 4 [select, 44 minutes]:
main.onReady.func1()
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/cmd/main.go:27 +0x1ee
created by main.onReady
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/cmd/main.go:16 +0x35

goroutine 20 [chan receive]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*mouseClickHandler).Start.func1(0xc0000a64e0, 0xc000082360, 0xc0000a40a0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseClickHandler.go:21 +0x77
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*mouseClickHandler).Start
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseClickHandler.go:19 +0xa1

goroutine 21 [chan receive]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*mouseCursorHandler).Start.func1(0xc0000a40a8, 0xc0000a64e0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseCursorHandler.go:26 +0x67
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*mouseCursorHandler).Start
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseCursorHandler.go:24 +0x75

goroutine 22 [select]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*screenChangeHandler).Start.func1(0xc0000a40b0, 0xc0000a64e0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/screenChangeHandler.go:33 +0x274
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*screenChangeHandler).Start
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/screenChangeHandler.go:24 +0x75

goroutine 23 [select]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/pkg/tracker.(*Instance).StartWithServices.func1(0xc0000a40b8, 0xc0000aa460)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/pkg/tracker/tracker.go:32 +0x158
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/pkg/tracker.(*Instance).StartWithServices
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/pkg/tracker/tracker.go:23 +0xf3

goroutine 24 [select]:
github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover.(*mouseMover).Start.func1(0xc0000a6540, 0xc0000aa460, 0xc00008ceb0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover/mouseMover.go:37 +0xe9
created by github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover.(*mouseMover).Start
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover/mouseMover.go:33 +0xb2

goroutine 75 [syscall, 44 minutes]:
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook._Cfunc_add_event(0xbe01170, 0x0)
        _cgo_gotypes.go:68 +0x49
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook.AddEvent(0x432b04c, 0x5, 0x0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook/hook.go:185 +0x76
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo.AddEvent(0x432b04c, 0x5, 0x0)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/go-vgo/robotgo/robotgo.go:1219 +0xf2
github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.addMouseClickRegistration(0xc0000a64e0, 0xc000082360)
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseClickHandler.go:59 +0x64
created by github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service.(*mouseClickHandler).Start.func1
        /Users/prashantgupta/go/src/github.com/prashantgupta24/automatic-mouse-mover/vendor/github.com/prashantgupta24/activity-tracker/internal/pkg/service/mouseClickHandler.go:27 +0x178
exit status 2
```
